"use client";
import "./globals.scss";
import { Inter, Roboto, Raleway, Lora, Ysabeau } from "next/font/google";
import Slider from "@/components/Slider";
import Header from "@/components/header";

import Footer from "@/components/Footer";
import Katalog from "../components/modals/Katalog";
import React from "react";
import { useRef, useState, useEffect } from "react";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next-Store.kz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isKatalogOpen, setIsKatalogOpen] = useState(false);

  const handleKatalogButtonClick = () => {
    setIsKatalogOpen(!isKatalogOpen);
    
  };
  return (
    <html lang="en">
      <>
        <body className={roboto.className}>
          <Header onKatalogButtonClick={handleKatalogButtonClick} />

          {isKatalogOpen && <Katalog />}

          <Slider></Slider>
          
            <main className="mainContent">{children}</main>
            
          <Footer />
        </body>
      </>
    </html>
  );
}
