"use client";
import "./globals.scss";
import { Inter, Roboto, Raleway, Lora, Ysabeau } from "next/font/google";
import Slider from "@/components/Slider";
import Header from "@/components/header";
import Home from "./page";
const lora = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next-Store.kz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <>
        <body className={lora.className}>
          <Header></Header>
          <Slider></Slider>
          <Home></Home>
        </body>
      </>
    </html>
  );
}
